# CodeRabbit Configuration
# Project: Ongils - PWA Shopping Mall
# Tech Stack: Next.js 16, TypeScript, React 19, Tailwind CSS

# General Settings
language: ko
early_access: false
enable_free_tier: true
tone_instructions: 'Technical and concise. Focus on Next.js 16 PPR, strict TypeScript (no any), performance, component structure, kebab-case naming, domain-based organization. Highlight a11y issues. Use Korean when appropriate.'

# Reviews Configuration
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: false # 속도 향상을 위해 비활성화
  auto_title_placeholder: '@coderabbitai'
  poem: false
  collapse_walkthrough: false
  review_status: true

  # Auto Review Settings
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT REVIEW'
      - 'Draft'
    drafts: false

  # Path Filters - Exclude unnecessary files from review
  path_filters:
    - '!**/*.json'
    - '!**/*.lock'
    - '!**/dist/**'
    - '!**/build/**'
    - '!**/.next/**'
    - '!**/node_modules/**'
    - '!**/public/**'

  # Path-Specific Instructions (핵심만 유지하여 속도 향상)
  path_instructions:
    - path: 'src/components/**/*.tsx'
      instructions: |
        - export default function 패턴 (화살표 함수 금지)
        - any 타입 금지
        - Client Component는 'use client' 필수

  # Tools Configuration
  tools:
    eslint:
      enabled: true

    markdownlint:
      enabled: false

    yamllint:
      enabled: false

    gitleaks:
      enabled: true

    # Disable non-relevant tools
    ruff:
      enabled: false

    biome:
      enabled: false

    hadolint:
      enabled: false

    swiftlint:
      enabled: false

    phpstan:
      enabled: false

    golangci-lint:
      enabled: false

    checkov:
      enabled: false

    detekt:
      enabled: false

    buf:
      enabled: false

    regal:
      enabled: false

    pmd:
      enabled: false

    cppcheck:
      enabled: false

    semgrep:
      enabled: false

    rubocop:
      enabled: false

# Chat Configuration
chat:
  auto_reply: true

# Knowledge Base Configuration
knowledge_base:
  opt_out: false

  learnings:
    scope: global

  code_guidelines:
    enabled: false # 속도 향상을 위해 비활성화 (AI prompt는 자동 생성되므로 영향 없음)
